CREATE TABLE banks (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) UNIQUE
);

CREATE TABLE reviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id NUMBER,
    review CLOB,
    rating NUMBER,
    review_date DATE,
    source VARCHAR2(50),
    sentiment_label VARCHAR2(20),
    sentiment_score FLOAT,
    keywords VARCHAR2(500),
    CONSTRAINT fk_bank FOREIGN KEY (bank_id) REFERENCES banks(id)
);



SELECT bank_id, COUNT(*) FROM reviews GROUP BY bank_id;
DELETE FROM REVIEWS;

SELECT user FROM dual;

SELECT table_name FROM user_tables;


ALTER TABLE reviews DROP COLUMN sentiment_score;
ALTER TABLE reviews ADD sentiment_score FLOAT;